### ISSUE TITLE
Leave suggestions in the suggestions channel for the public to see

### ISSUE THREAD

**Issue by mralext20** [BlobEmoji/queuebot#10]
this is a QOL change that will allow anyone in the server to see what has been submited, like tihngs were before, with b1nb0t, and with manual processing.

**Comment by slice** [comment]
How about just adding a reaction (like :eyes:) to the message, then delete when it gets denied/approved?

**Comment by mralext20** [comment]
that would probably also work just as well

**Comment by ThaTiemsz** [comment]
I think the suggestions should be left in the channel. I think it used to be this way, but to be honest I can't recall really it's been so long

**Comment by mralext20** [comment]
Can this be marked as a higher priority?

It's especially annoying for the general public to see unreadable where there's no new messages
