### ISSUE TITLE
Add the suggestion ID to the emoji name

### ISSUE THREAD

**Issue by ThaTiemsz** [BlobEmoji/queuebot#16]
So for the emoji name for suggestion `:bloblol:` would be e.g. `:bloblol_55:` or something like that. Easier to know what the suggestion ID is, instead of running the `q!sg` command.

**Comment by Gorialis** [comment]
I don't think adding the ID to the emoji name is the best approach for this. It might be better just to include the ID in the message separate from the name wherever it appears.

**Comment by ThaTiemsz** [comment]
The emoji won't be jumbo'd then, though.

**Comment by ThaTiemsz** [comment]
I'm okay with just looking in the suggestion log channel, closing this.
