### ISSUE TITLE
A proposal to remove ambiguity from VS votes

### ISSUE THREAD

**Issue by memethyl** [BlobEmoji/queuebot#32]
---

Current VS vote system: 
![Current system](https://i.imgur.com/5pMV6M4.png)

The main downside to this vote system is that because of the strange way Discord sorts reactions, an emote creator could have their emote resubmission denied not because of the quality of the resubmission itself, but because people erroneously thought the reactions were in order (left one then right one), when in reality they were _the other way around._

---

Proposed VS vote system: 
![Proposed system](https://i.imgur.com/o981T7Y.png)

This proposal fixes the aforementioned problem by having the emotes being voted on represented as 1 and 2, so that even if the reactions get sorted incorrectly, it's impossible to get them confused.

---

**Comment by mralext20** [comment]
even better: default emojis don't get reordered by the reordering bug
