### ISSUE TITLE
Bot doesn't take commands and creating a suggestion breaks the bot

### ISSUE THREAD

**Issue by ElijahPepe** [BlobEmoji/queuebot#46]
# Steps to Reproduce

1. Follow the Debian 10 instructions as provided in the README.md file.
2. Run the bot using Python 3.6.
3. Create a submission in the channel of choice.

# Expected Behavior

I should just be able to carry on and deny/approve submissions either using reactions or commands.

# Actual Behavior

The bot stops accepting commands and reactions no longer work.

# Error Message

```1|queuebot  | 2020-07-28 21:50:43,858:DEBUG:queuebot.cogs.queue: Message content: ":tipsfedora:", detected name: "tipsfedora", detected note: "None"
1|queuebot  | 2020-07-28 21:50:44,158:INFO:queuebot.cogs.queue: Created new emoji by name tipsfedora in guild 737756609324908624.
1|queuebot  | 2020-07-28 21:50:44,169:INFO:queuebot.cogs.queue: Producing a test image...
1|queuebot  | 2020-07-28 21:50:44,589:ERROR:queuebot.cogs.errors: Error in on_on_message:
1|queuebot  | Traceback (most recent call last):
1|queuebot  |   File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 312, in _run_event
1|queuebot  |     await coro(*args, **kwargs)
1|queuebot  |   File "/queuebot/queuebot/cogs/queue/__init__.py", line 224, in on_message
1|queuebot  |     await self.handle_suggestion_message(message)
1|queuebot  |   File "/queuebot/queuebot/cogs/queue/__init__.py", line 192, in handle_suggestion_message
1|queuebot  |     await msg.add_reaction(self.config.approve_emoji)
1|queuebot  |   File "/usr/local/lib/python3.7/dist-packages/discord/message.py", line 953, in add_reaction
1|queuebot  |     await self._state.http.add_reaction(self.channel.id, self.id, emoji)
1|queuebot  |   File "/usr/local/lib/python3.7/dist-packages/discord/http.py", line 245, in request
1|queuebot  |     raise HTTPException(r, data)
1|queuebot  | discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
```
***

No error message is provided when using a command, the commands simply do not work.

***

## Config.YAML Settings

```# Emoji info
approve_emoji_id: 737764731087093760
deny_emoji_id: 735300726573498428

approve_emoji: 'upvote:737764731087093760'
deny_emoji: 'downvote:735300726573498428'
```

# System Configuration

## Operating System

Debian 10.3, on a 64-bit version.

### Kernel Release

4.19.0-8-cloud-amd64

### CPU

Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz

### RAM

16 GB DDR4 RAM at 3200 Mhz

## PostGresSQL Port

5432 with a timeout of 60.

## Impact

This is a high severity bug no matter how you slice it.

**Comment by SnowyLuma** [comment]
This seems to be a configuration mistake on your part, not a "high severity bug," as the bot works fine for other users.

The error message from the API is a bit misleading, however this is most likely due to your bot user not being in the guild the emoji are from, and thus has no permission to use them.

**Comment by ElijahPepe** [comment]
The emojis are from my own Discord and the bot is in the Discord.

**Comment by SnowyLuma** [comment]
Well then I would suggest using emoji which you have not deleted yet.

**Comment by ElijahPepe** [comment]
I didn't delete it.

**Comment by SnowyLuma** [comment]
I'm unable to further help you with this. It's pretty easy to test whether an emoji exists, or has ever existed in the first place, and your emoji fail both of theses tests. If you have a different issue that is actually actionable feel free to come back.

**Comment by ElijahPepe** [comment]
I also tried it with :green_check_mark: and :x: and both were also giving the same result. This is not an emoji not existing issue.
