### ISSUE TITLE
Move q!eval/q!buffer_info etc. into the Bot Administration category 

### ISSUE THREAD

**Issue by slice** [BlobEmoji/queuebot#7]

**Comment by Gorialis** [comment]
"Bot Administration" isn't an actual category, it's the docstring of a command group, so the idea behind this is confusing (do you want to merge eval into the `wrench` group?). If we're keeping them under the same commands, I'm inclined to remove the Utilities cog and move all of these under a new cog with a custom category name.

**Comment by slice** [comment]
Irrelevant because we just Jishaku now.
