### ISSUE TITLE
Track reactions in the council-queue

### ISSUE THREAD

**Issue by SuperSajuuk** [BlobEmoji/queuebot#8]
Something that might be useful to reduce the burden on finding if someone is inactive or not is to track the last time someone added a reaction in the council-queue. By doing this, we can partially automate the council-queue in that, if a council members stops adding reactions, we can determine if they are inactive (eg if the last time someone added a reaction was a month ago, remove the role automatically).

This could potentially lead the way for automating the addition of the role when a suggestion is fully approved in a similar way, making it easier on police overall.

**Comment by slice** [comment]
Currently, the bot only tracks the number of upvotes and downvotes — not who added them. This will require a restructure of the bot's database schema.

**Comment by slice** [comment]
CC @FrostLuma

**Comment by slice** [comment]
- [ ] Restructure the bot's internal schema
- [ ] Add code to track users who react somehow
- [ ] Make sure that this only applies to #council-queue, not #approval-queue
- [ ] Add a command to view who upvoted/downvoted an emoji
- [ ] Automatically warn/remove roles, etc. maybe with some human intervention

**Comment by JustMaffie** [comment]
To be honest I don't think demotions should ever be automatic, however warnings could be automatic, but its just not right to get demoted automatically, humans are always more accurate, and what if someone goes on vacation and can't get on discord for a month?

**Comment by SuperSajuuk** [comment]
It was an example, nobody said we planned on demoting people automatically via the bot, like you can see in slice's comment about how it's planned.

The whole premise of this ticket is to document the automation of the Council Queue and how we can track council activity with the queue itself.
